#!C:\Program Files\Python310\python.exe
import cgi, cgitb
#import Mysqldb
cgitb.enable()
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("    <title> RESPIRATORY ILLNESS </title>")
print("   ")
print("    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>")
print("<script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>")
print("<script src='https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js' integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q' crossorigin='anonymous'></script>")
print("<link rel='stylesheet' href='dot.css'>")
print("<body style = 'background: url(https://pikbest.com/backgrounds/white-abstract-background.-backdrop-for-presentation-design-for-website_1772526.html)'> ") 
print("</head>")
print("")
print("<body>")
print("    <div>  ")
print("        <nav class='navbar navbar-expand-sm navbar-light' style='background-color:#98FB98'>")
print("            <a class='navbar-brand' >")
print("                <img src='logo.png' width='100' height='100' /> RESPIRATORY ILLNESS </a>")
print("            <ul class='navbar-nav ml-auto'>")
print("                <li class='nav-item'>")
print("                    <a class='nav-link' href='main.py'>Home</a>")
print("                </li>")
print("				        <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>About </a>")
print("                </li>")
print("				        <li class='nav-item'>")
print("                    <a class='nav-link' href='contact.py'>Contact us</a>")
print("                </li>")
print("            </ul>")
print("        </nav>")
print("    </div><br>")
print("<div class='content container'>")
print("<b><u><h1><center> &nbsp &nbsp &nbsp &nbsp &nbsp'Python in Healthcare and patient condition  management' </center></h1></u></b><br><br><br>")
print("</div>")
print("		<div style='max-width: 90%;padding-left: 20%;'>")
print("<h4> We are students of Sriramachandra university motivated to do our project in computer science domain under the department of bioinformatics. Our mission is to make the website useful for the medical community and the common people to assess their condition after being diagnosed by a medical professional.<br><br> ")
print("This website would serve as assessment tool for doctors and individuals adready diagnosed with the condition , The prediction tool can be used as a second confirmation of the disease . To add on , this webpage contains information on recent respiratory related and climatic change . </h4> ")