#!C:\Program Files\Python310\python.exe
import cgi, cgitb
#import Mysqldb
cgitb.enable()

f=cgi.FieldStorage()
inlineRadioOptions1=f.getvalue('inlineRadioOptions1', -1)
inlineRadioOptions2=f.getvalue('inlineRadioOptions2', -1)
inlineRadioOptions3=f.getvalue('inlineRadioOptions3', -1)
inlineRadioOptions4=f.getvalue('inlineRadioOptions4', -1)
inlineRadioOptions5=f.getvalue('inlineRadioOptions5', -1)
inlineRadioOptions6=f.getvalue('inlineRadioOptions6', -1)
inlineRadioOptions7=f.getvalue('inlineRadioOptions7', -1)
inlineRadioOptions8=f.getvalue('inlineRadioOptions8', -1)

total = int(inlineRadioOptions1)
total += int(inlineRadioOptions2)
total += int(inlineRadioOptions3)
total += int(inlineRadioOptions4)
total += int(inlineRadioOptions5)
total += int(inlineRadioOptions6)
total += int(inlineRadioOptions7)
total += int(inlineRadioOptions8)

if total >= 0 and total <= 10:
	result = "<b><h2>Exaceberation level :  0 - 10 (LOW)</h2></b> <h4>1. Quit smoking,<br> 2. Reduce exposure to exacerbation risk factors like tobacco smoke,chemicals,fumes <br> 3. consider LAMA/LABA rescue inhalers<br></h4>  "
elif total >= 11 and total <= 20:
	result = "<b><h2>Exaceberation level : 11 - 20 (MEDIUM)</h2></b> <h4> 1. Quit smoking,<br> 2. Reduce exposure to exacerbation risk factors like tobacco smoke,chemicals,fumes <br> 3. consider LAMA/LABA rescue inhalers<br>4. referrals for pulmonary rehabilitation <br>5. possible lung transplant option evaluation<br></h4>"
elif total >= 21 and total <= 30:
	result = "<b><h2>Exaceberation level : 21 - 30 (HIGH)</h2></b> <h4>1. Quit smoking,<br> 2. Reduce exposure to exacerbation risk factors like tobacco smoke,chemicals,fumes <br> 3. consider LAMA/LABA rescue inhalers<br>4. referrals for pulmonary rehabilitation <br>5. possible lung transplant option evaluation<br>6. oxygen supplementation<br></h4>"
elif total >= 31 and total <= 40:
	result = "<b><h2>Exaceberation level : 31 - 40 (VERY HIGH)</h2></b> <h4>1. Quit smoking,<br> 2. Reduce exposure to exacerbation risk factors like tobacco smoke,chemicals,fumes <br> 3. consider LAMA/LABA rescue inhalers<br>4. referrals for pulmonary rehabilitation <br>5. possible lung transplant option evaluation<br>6. oxygen supplementation<br></h4>"
else:
	result = ""

print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("    <title> RESPIRATORY ILLNESS </title>")
print("   ")
print("    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>")
print("<script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>")
print("<script src='https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js' integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q' crossorigin='anonymous'></script>")
print("<link rel='stylesheet' href='dot.css'>")
print("</head>")
print("")
print("<body>")
print("    <div>  ")
print("        <nav class='navbar navbar-expand-sm navbar-light' style='background-color:#98FB98'>")
print("            <a class='navbar-brand' >")
print("                <img src='logo.png' width='100' height='100' /> RESPIRATORY ILLNESS </a>")
print("            <ul class='navbar-nav ml-auto'>")
print("                <li class='nav-item'>")
print("                    <a class='nav-link' href='main.py'>Home</a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>About </a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>Contact us</a>")
print("                </li>")
print("            </ul>")
print("        </nav>")
print("    </div>")
print("")
print("		")
print("    </div>")
print("	<br/>")
print("	<div class='container'>")
print("		<div>")
print("			<center><h3><b>COPD SEVERITY ASSESSMENT</b></h3></center>")
print("		</div>")
print("		<br/>")
print("		<div class='row'>")
print("		<div class='col-sm'>")
print("		<form action='chronicpul.py' method='GET/POST'>")
print("		  <div class='form-group'>")
print("			<label for='q1'><b><i>Q1.	Frequency of cough</i></b></label>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions1' id='inlineRadio0' value=0 checked checked>")
print("			  <label class='form-check-label' for='inlineRadio0'>0</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions1' id='inlineRadio1' value=1>")
print("			  <label class='form-check-label' for='inlineRadio1'>1</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions1' id='inlineRadio2' value=2>")
print("			  <label class='form-check-label' for='inlineRadio2'>2</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions1' id='inlineRadio3' value=3>")
print("			  <label class='form-check-label' for='inlineRadio3'>3</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions1' id='inlineRadio4' value=4>")
print("			  <label class='form-check-label' for='inlineRadio4'>4</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions1' id='inlineRadio5' value=5>")
print("			  <label class='form-check-label' for='inlineRadio5'>5</label>")
print("			</div>")
print("		  </div>")
print("		  ")
print("		<div class='form-group'>")
print("			<label for='q2'><b><i>Q2. Difficulty in bring up sputum on coughing</b></i></label>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions2' id='inlineRadio0' value=0 checked checked>")
print("			  <label class='form-check-label' for='inlineRadio0'>0</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions2' id='inlineRadio1' value=1>")
print("			  <label class='form-check-label' for='inlineRadio1'>1</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions2' id='inlineRadio2' value=2>")
print("			  <label class='form-check-label' for='inlineRadio2'>2</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions2' id='inlineRadio3' value=3>")
print("			  <label class='form-check-label' for='inlineRadio3'>3</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions2' id='inlineRadio4' value=4>")
print("			  <label class='form-check-label' for='inlineRadio4'>4</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions2' id='inlineRadio5' value=5>")
print("			  <label class='form-check-label' for='inlineRadio5'>5</label>")
print("			</div>")
print("		  </div>")
print("		  ")
print("		<div class='form-group'>")
print("			<label for='q3'><b><i>Q3. Chest tightness (crushing/pressure/squeezing)</b></i></label>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions3' id='inlineRadio0' value=0 checked>")
print("			  <label class='form-check-label' for='inlineRadio0'>0</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions3' id='inlineRadio1' value=1>")
print("			  <label class='form-check-label' for='inlineRadio1'>1</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions3' id='inlineRadio2' value=2>")
print("			  <label class='form-check-label' for='inlineRadio2'>2</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions3' id='inlineRadio3' value=3>")
print("			  <label class='form-check-label' for='inlineRadio3'>3</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions3' id='inlineRadio4' value=4>")
print("			  <label class='form-check-label' for='inlineRadio4'>4</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions3' id='inlineRadio5' value=5>")
print("			  <label class='form-check-label' for='inlineRadio5'>5</label>")
print("			</div>")
print("		  </div>")
print("		  ")
print("		<div class='form-group'>")
print("			<label for='q4'><b><i>Q4. Chest congestion (chest feeling heavy)</b></i></label>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions4' id='inlineRadio0' value=0 checked>")
print("			  <label class='form-check-label' for='inlineRadio0'>0</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions4' id='inlineRadio1' value=1>")
print("			  <label class='form-check-label' for='inlineRadio1'>1</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions4' id='inlineRadio2' value=2>")
print("			  <label class='form-check-label' for='inlineRadio2'>2</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions4' id='inlineRadio3' value=3>")
print("			  <label class='form-check-label' for='inlineRadio3'>3</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions4' id='inlineRadio4' value=4>")
print("			  <label class='form-check-label' for='inlineRadio4'>4</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions4' id='inlineRadio5' value=5>")
print("			  <label class='form-check-label' for='inlineRadio5'>5</label>")
print("			</div>")
print("		  </div>")
print("		  ")
print("		<div class='form-group'>")
print("			<label for='q5'><b><i>Q5. Shortness of breath on performing indoor activities</b></i></label>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions5' id='inlineRadio0' value=0 checked>")
print("			  <label class='form-check-label' for='inlineRadio0'>0</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions5' id='inlineRadio1' value=1>")
print("			  <label class='form-check-label' for='inlineRadio1'>1</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions5' id='inlineRadio2' value=2>")
print("			  <label class='form-check-label' for='inlineRadio2'>2</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions5' id='inlineRadio3' value=3>")
print("			  <label class='form-check-label' for='inlineRadio3'>3</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions5' id='inlineRadio4' value=4>")
print("			  <label class='form-check-label' for='inlineRadio4'>4</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions5' id='inlineRadio5' value=5>")
print("			  <label class='form-check-label' for='inlineRadio5'>5</label>")
print("			</div>")
print("		  </div>")
print("		  ")
print("		<div class='form-group'>")
print("			<label for='q6'><b><i>Q6. Shortness of breath on performing outdoor activities</i></b></label>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions6' id='inlineRadio0' value=0 checked>")
print("			  <label class='form-check-label' for='inlineRadio0'>0</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions6' id='inlineRadio1' value=1>")
print("			  <label class='form-check-label' for='inlineRadio1'>1</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions6' id='inlineRadio2' value=2>")
print("			  <label class='form-check-label' for='inlineRadio2'>2</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions6' id='inlineRadio3' value=3>")
print("			  <label class='form-check-label' for='inlineRadio3'>3</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions6' id='inlineRadio4' value=4>")
print("			  <label class='form-check-label' for='inlineRadio4'>4</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions6' id='inlineRadio5' value=5>")
print("			  <label class='form-check-label' for='inlineRadio5'>5</label>")
print("			</div>")
print("		  </div>")
print("		  ")
print("		<div class='form-group'>")
print("			<label for='q7'><b><i>Q7. Tiredness or weakness</i></b></label>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions7' id='inlineRadio0' value=0 checked>")
print("			  <label class='form-check-label' for='inlineRadio0'>0</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions7' id='inlineRadio1' value=1>")
print("			  <label class='form-check-label' for='inlineRadio1'>1</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions7' id='inlineRadio2' value=2>")
print("			  <label class='form-check-label' for='inlineRadio2'>2</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions7' id='inlineRadio3' value=3>")
print("			  <label class='form-check-label' for='inlineRadio3'>3</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions7' id='inlineRadio4' value=4>")
print("			  <label class='form-check-label' for='inlineRadio4'>4</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions7' id='inlineRadio5' value=5>")
print("			  <label class='form-check-label' for='inlineRadio5'>5</label>")
print("			</div>")
print("		  </div>")
print("		  ")
print("		  		  <div class='form-group'>")
print("			<label for='q8'><b><i>Q8. Sleep disturbance</i></b></label>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions8' id='inlineRadio0' value=0 checked>")
print("			  <label class='form-check-label' for='inlineRadio0'>0</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions8' id='inlineRadio1' value=1>")
print("			  <label class='form-check-label' for='inlineRadio1'>1</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions8' id='inlineRadio2' value=2>")
print("			  <label class='form-check-label' for='inlineRadio2'>2</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions8' id='inlineRadio3' value=3>")
print("			  <label class='form-check-label' for='inlineRadio3'>3</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions8' id='inlineRadio4' value=4>")
print("			  <label class='form-check-label' for='inlineRadio4'>4</label>")
print("			</div>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='inlineRadioOptions8' id='inlineRadio5' value=5>")
print("			  <label class='form-check-label' for='inlineRadio5'>5</label>")
print("			</div>")
print("")
print("</div>")
print("		</div>")
print("		<div class='col-sm'>")
print("			<div class='card'>")
print("			  <div class='card-body'>")
print("				<h6 class='card-title'><u><b>0 - Never</b></u></h6>")
print("				<h6 class='card-title'><u><b>1 - Low</b></u></h6>")
print("				<h6 class='card-title'><u><b>2 - Slight</b></u></h6>")
print("				<h6 class='card-title'><u><b>3 - Moderate</b></u></h6>")
print("				<h6 class='card-title'><u><b>4 - Often</b></u></h6>")
print("				<h6 class='card-title'><u><b>5 - Frequently</b></u></h6>")
print("</div>")
print("			</div>")
print("</div>")
print(" ")
print("<br/><br/>")
print("		  </div>")
print("")
print("			<button type='submit' class='btn btn-primary'>Submit</button>")
print("  <br/><br/>")
print("		</form>")	
print("  ")
print("  ")
print("		</div>")
print("		<div class='col-sm'>")
print("			<div class='card'>")
print("				<div><h5><b>Your result will show up here!</b></h5></div>")
print("				<div>")
print("<h1>{}</h1>".format(result))
print("				</div>")
print("				</div>")
print("			  			</div>")
print("</div>")
print("<br/><br/><br/><br/>")
print("")
print("			")
print("		</div>")
print("	</div>")
print("</body>")
print("</html>")	