#!C:\Program Files\Python310\python.exe
import cgi, cgitb
#import Mysqldb
cgitb.enable()
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("    <title> RESPIRATORY ILLNESS </title>")
print("   ")
print("    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>")
print("<script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>")
print("<script src='https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js' integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q' crossorigin='anonymous'></script>")
print("<link rel='stylesheet' href='dot.css'>")
print("</head>")
print("")
print("<body>")
print("    <div>  ")
print("        <nav class='navbar navbar-expand-sm navbar-light' style='background-color:#98FB98'>")
print("            <a class='navbar-brand' >")
print("                <img src='logo.png' width='100' height='100' /> RESPIRATORY ILLNESS </a>")
print("            <ul class='navbar-nav ml-auto'>")
print("                <li class='nav-item'>")
print("                    <a class='nav-link' href='main.py'>Home</a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>About </a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>Contact us</a>")
print("                </li>")
print("            </ul>")
print("        </nav>")
print("    </div>")
print("")
print("    </div>")
print("	")
print("	")
print("")
print(" <div class='wrapper'>")
print("        <!--Top menu -->")
print("        <div class='sidebar' style='max-width: 20%;'>")
print("           <!--profile image & text-->")
print("            <!--menu item-->")
print("			<ul>")
print("                <li>")
print("                    <a href='#' class='active'>")
print("                        <span class='item'>Introduction</span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#Health concerns' class = 'active'>")
print("                        <span class='item'>Health concerns</span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#Air Quality'>")
print("                        <span class='item'>Air Quality</span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#Aeroallergens'>")
print("                        <span class='item'>Aeroallergens</span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#PM2.5'>     ")
print("                        <span class='item'>PM2.5</span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#Delhi air pollution'>")
print("                        <span class='item'>Delhi air pollution</span>")
print("                    </a>")
print("                </li>")
print("        </div>")
print("		<div style='max-width: 80%;padding-left: 20%;'>")
print("<h1><b><center><u>&nbsp &nbsp &nbsp &nbsp Rising Climate change issues and Health concerns</CENTER></b></h1>")
print("            <br><br><h5>Climate change is increasing the frequency and severity of floods, droughts, heat waves, and blizzards. Extreme heat is projected to cause increased deaths and could lead to more frequent droughts. Climate change will not necessarily lead to warmer winters, but winters with more extreme blizzards. Increased precipitation will lead to more floods. Flooding can increase mold and fungi growth, which can exacerbate asthma and allergies. In addition to these direct harms, extreme weather events can physically limit people access to care, medical supplies, and necessary services.<br><img src='climate.jpg' height='200' width='300' align = 'right'> Science shows that an increase in average global temperature by more than two degrees Celsius above pre-industrial levels risks human health. Accelerating climate change poses a particular threat to people living with chronic disease, including respiratory issues like asthma, chronic obstructive pulmonary disease (COPD), allergies, emphysema, and lung cancer.<h5>")
print("<h5>While nations work to reduce greenhouse gasses by 80 percent by 2050 in order to curb many of these health consequences, some effects are inevitable and persons living with respiratory disease and their caretakers will need to adapt to a changing climate.</h5>")
print("")
print("            <br/>")
print("")
print("")
print("")
print("           </h4>")
print("            <br/>")
print("            <div id='Health concerns'>")
print("<h3>Health concerns</h3>")
print("<br>")
print("<li>1. Power outages in extreme weather could cripple hospitals and transportation systems when we need them most.</li>")
print("<li>2. Crop declines could lead to undernutrition, hunger, and higher food prices. More CO2 in the air could make staple crops like barley and soy less nutritious.</li>")
print("<li>3. Occupational hazards such as risk of heatstroke will rise, especially among farmers and construction workers. Labor could shift to dawn and dusk, times when more disease carrying insects are out.</li>")
print("<li>4. Trauma from floods, droughts, and heat waves can lead to mental health issues like anxiety, depression, and suicide.</li>")
print("<li>5. More heat can mean longer allergy seasons and more respiratory disease. More rain increases mold, fungi, and indoor air pollutants.</li>")
print("            </div>")
print("            <br/>")
print("            <div id='Air Quality'>")
print("<h3>Air Quality</h3>")
print("Climate change and air pollution are intrinsically connected since greenhouse gases and air pollutants originate from the same source, fossil fuel combustion. In fact, combustion processes emit both greenhouse gases, like carbon dioxide (CO2), methane (CH4) and nitrous oxide (N2O), and air pollutants, like particulate matter (PM), sulfur dioxide (SO2), nitrogen dioxide (NO2) and carbon monoxide (CO).<br/>")
print("At both a global and a regional level, now and in the future, climate change and air pollution trends counterbalance in determining air quality: on the one hand, a reduction in anthropogenic emissions, resulting from the implementation of the emission control legislation adopted in each country and energetic sector improvements; on the other hand, climate change effects, in most cases leading to an increase in pollution levels.<img src='pollution.png' height='320' width='450' align = 'right'><br>")
print(" <br>The correlation between climate and air quality is noteworthy for ozone. Ozone levels are directly driven by weather since ozone-generating photochemical reactions of air pollutants (nitrogen oxides; methane; volatile organic compounds, VOCs) need high temperatures and bright sunshine, conditions typical of summer months.")
print("  Carbon monoxide, non-methane VOCs and nitrogen oxides cause a reduction in the oxidant power of the atmosphere increasing the lifetime of methane, one of the most important warming agents and a precursor to ozone .           <br/>")
print(" Nitrate particles, as well as organic carbon aerosols, instead have a cooling effect on the climate. Sulfur dioxide partly converts to sulfate particles, which also have cooling potential, and partly reacts with black carbon, which has a strong warming effect . <br/>")
print("            <br/>")
print("            <br/>")
print("<div id='Aeroallergens'>")
print("<h3>Aeroallergens</h3>")
print("  The higher levels of carbon dioxide and the resulting warming climate are also likely to worsen the global burden of allergic diseases, mainly through the anticipation in time of the onset of warmer seasons and thus of the concentration of aeroallergens (pollen).<img src='aeroallergen.png' height='320' width='450' align = 'right'><br/>")
print("Increases in ambient pollen concentrations are associated with higher rates of allergic sensitization, higher numbers of emergency department visits and hospital admissions for asthma and allergic rhinitis, as well as higher numbers of physician office visits for allergic diseases.<br/>")
print("An example is represented by the health effects of the common ragweed (Ambrosia artemisiifolia), a flowering plant that spreads very vigorously due to global warming. Beside reducing crop yields, this invasive plant produces very aggressive pollens that cause severe allergic reactions among those sensitive, including one in 5 Europeans who suffer from allergies, one in 7 of those with rhinitis and one in 11 with asthma .<br/>")
print("            <br/>")
print("            <br/>")
print("<div id='PM2.5'>")
print("<h3>PM2.5</h3>")
print("  Excessive amounts of gases like carbon dioxide, carbon monoxide, sulphur dioxide, nitrogen oxides, methane and chlorofluorocarbons, suspended particulates, among others, make air pollution a many-headed Hydra. <br/>")
print("   While an excess of any pollutant in the air is bad news and negatively affects our health, the bulk of respiratory illnesses from pollution are owing to one category small particulate matter (PM2.5 or particulate matter smaller than 2.5 microns).         <br/>")
print("    PM10 (or particulate matter smaller than 10 microns) is another category of particulate pollutants that includes aerosols and particulate matter. These two measures and the ratio between them vary from city to city and source to source, making them a good indicator of the source of pollution locally.        <br/>")
print("            <br/><br/>")
print("<div id='Delhi air pollution'>")
print("<h3>Delhi air pollution</h3>")
print("    Delhi's air quality in May this year was the poorest for the month in the last three years, according to the Central Pollution Control Board data.       <br/>")
print("    Experts attributed the poor air quality to the lack of rainfall in the first half of the month.The city received just 1.4 mm of rainfall from May 1 to May 20, according to the India Meteorological Department.Delhi recorded an average air quality index (AQI) of 212 this year as against 144 in 2021 and 143 in 2020.It saw 21 days of poor air quality in 2022 as compared to three in 2021 and just two in 2020.The capital had only one day of satisfactory air quality this time as against six in 2021 and four in 2020.")
print("Moderate air quality days also dipped to nine as compared to 22 such days last year.An AQI between 201 and 300 is considered 'poor', 301-400 'very poor' and 401-500 'severe', while the AQI above 500 falls in the 'severe plus' category.<br><br> ")
print("<img src='delhi.jpg' height='320' width='350' align = 'left'><img src='DelhiAirPollution-2.jpg' height='320' width='450' align = 'right'>")
print(" Particulate matters (PM) 2.5 and 10 remained at least five times more their safe standards. These ultrafine particles can enter the respiratory system and reach the bloodstream.<br/>")
print(" On an average, a person breathes 25,000 times a day. For those living in Delhi and the National Capital Territory (NCT) regions, this means breathing toxic air 25,000 times a day. Toxins once deposited in lungs cannot be cleansed. According to doctors, such continued inhalation of toxic gases affects all organs and not just lungs. It even has the potential to cause hormonal imbalances. Being in such an environment full of pollutants constantly also affects the central nervous system of the brain. <br/>")
print("  The biggest positive step taken by the Delhi government was to permanently shut down the old, polluting Badarpur coal-fired power plant in the southeastern outskirts of Delhi. The plant, a major cause of the Capital Region's air pollution, had been shut down every winter for the past three years as a way to scale back pollution. <br/>")
print("   The government is taking steps to improve air quality, but they are still small and scattered. According to TERI, several concerted, combined measures could cut particulate pollution in Delhi by half. Turning agricultural residue into profitable products could reduce PM2.5 levels in the winter by 12%.          <br/>")
print(" A more reliable supply of grid electricity to avoid running diesel generators and more clean-burning liquefied petroleum gas cooking stoves to replace biomass burning would cut levels by 13.7%. Enforcing pollution standards for industries and introducing 8,000 electric buses would cut another 10.5%.<br/>")
print("        </div>")
print("    </div>")
print(" </body>")
print(" </html>")
