#!C:\Program Files\Python310\python.exe
import cgi, cgitb
#import Mysqldb
cgitb.enable()
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("    <title> RESPIRATORY ILLNESS </title>")
print("   ")
print("    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>")
print("<script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>")
print("<script src='https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js' integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q' crossorigin='anonymous'></script>")
print("<link rel='stylesheet' href='dot.css'>")
print("</head>")
print("")
print("<body>")
print("    <div>  ")
print("        <nav class='navbar navbar-expand-sm navbar-light' style='background-color:#98FB98'>")
print("            <a class='navbar-brand' >")
print("                <img src='logo.png' width='100' height='100' /> RESPIRATORY ILLNESS </a>")
print("            <ul class='navbar-nav ml-auto'>")
print("                <li class='nav-item'>")
print("                    <a class='nav-link' href='main.py'>Home</a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>About </a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>Contact us</a>")
print("                </li>")
print("            </ul>")
print("        </nav>")
print("    </div>")
print("")
print("	")
print("	")
print("<h1><b><center><u>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp EMERGING ISSUES IN THE RESPIRATORY DISEASES</CENTER></b></h1>")
print("")
print(" <div class='wrapper'>")
print("        <!--Top menu -->")
print("        <div class='sidebar' style='max-width: 20%;'>")
print("           <!--profile image & text-->")
print("            <!--menu item-->")
print("			<ul>")
print("                <li>")
print("                    <a href='#INTRODUCTION' class='active'>")
print("                        <span class='item'> INTRODUCTION</span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#LUNG HEALTH FACTS' class='active'>")
print("                        <span class='item'>LUNG HEALTH FACTS </span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#EMERGING ISSUES' class = 'active'>")
print("                        <span class='item'>EMERGING ISSUES </span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#RESPIRATORY DISEASE PREVENTION' class='active'>")
print("                        <span class='item'>RESPIRATORY DISEASE PREVENTION</span>")
print("                    </a>")
print("                </li>")
print("        </div>")
print("		<div style='max-width: 80%;padding-left: 20%;'><br>")
print("            <div id='INTRODUCTION'>")
print("<h4>INTRODUCTION </h4>")
print("            <h5>CRDs represent a group of diseases characterized by abnormal conditions of the respiratory system, Chronic respiratory diseases include COPD, asthma, pneumoconiosis, interstitial lung diseases and pulmonary sarcoidosis which affect all ages. COPD is one of the leading non-communicable causes of death globally as well as India. According to the global burden of disease study 1990-2016, the contribution of CRDs to the total DALYs in India increased from 4.5% in 1990 to 6.4% in 2016.</h5>")
print("")
print("            <h5>COPD and asthma were responsible for 75.6% and 20% of CRD DALYs. The DALYs per case of COPD and asthma were 1.7 and 2.4 times higher in India in 2016 i.e. Most states had higher rates compared with other locations worldwide at similar levels of socio-demographic index. The increasing contribution of these diseases to all the overall disease burden across India and the high rate of health loss from them, especially in the less-developed low ETL states, highlights the need for focused policy interventions to address this significant cause of disease burden in India.</h5>")
print("           <h5><br> <br/> Main Risk Factors:<br>")
print("1.Tobacco smoking<br>")
print("2.Air pollution<br>")
print("3.Allergens<br>")
print("4.Occupational risks<br>")
print("5.Vulnerability<br>")
print("6.Occupational chemicals and dust<br>")
print("7.Frequent lower respiratory tract infections during childhood <br><br></h5>")
print("            <h4>Global Alliance against CRDs:</h4>")
print("            <h5>GARD contributes to WHOs global work to prevent and control CRDs.It is a voluntary alliance of national and international organizations from a range of countries working together to achieve a common goal of reducing the global burden of CRDs.</h5>")
print("<br><br>")
print("            <div id='LUNG HEALTH FACTS'>")
print("<h3>LUNG HEALTH FACTS</h3>")
print("<ul><h5>")
print("<li>• 384 million people suffer from chronic obstructive pulmonary disease (COPD) and 3 million die from it each year, making it the third leading cause of death worldwide.<br></li>")
print("<li>• 10 million people develop tuberculosis and 1.6 million die from it each year, making it the most common lethal infectious disease.<br></li>")
print("<li>• 1.76 million people die from lung cancer each year, making it the most deadly cancer and 334 million people suffer from asthma.<br></li>")
print("<li>• Asthma is the most common chronic disease of childhood, affecting 14 percent of children globally and rising<br></li>")
print("<li>• 4 million people die from lower respiratory tract infections and pneumonia each year . Every minute, 2 children under 5 years old die from pneumonia.<br></li>")
print("<li>• 80 percent of pneumonia deaths are in children under 2 years.<br></li>")
print("<li>• Most (99 percent) deaths occur in low or middle-income countries <br></li>")
print("<li>• Pneumonia is the leading cause of death in the very young and very old.</li>")
print("<li>• Passive smoke exposure also leads to respiratory disease. Since 1964, about 2.5 million nonsmokers have died from health problems caused by exposure to second-hand smoke.<br></li>")
print("<li>• 4.2 million people die every year as a result of exposure to ambient (outdoor) air pollution.<br></li>")
print("<li>• 3.8 million people die every year as a result of household exposure to smoke from dirty cookstoves and fuels.<br></li>")
print("<li>• 91 percent of the world’s population live in places where air quality exceeds WHO guideline limits.<br></li></h5>")
print("<br><br><br>")
print("            <div id='EMERGING ISSUES'>")
print("<h3>EMERGING ISSUES IN RESPIRATORY DISEASES</h3>")
print("<h5>Idiopathic pulmonary fibrosis, sarcoidosis, respiratory distress syndromes, and upper airway conditions such as rhinitis and chronic sinusitis. In some cases, effective preventive interventions do not exist. In others, nationally representative trend data for disease prevalence and/or incidence, causative exposures, and other preventable risk factors are not available for tracking of measurable goals. It is hoped that, as preventive interventions and surveillance for respiratory hazards and diseases continue to improve, future versions of Healthy People will include measurable goals for at least some of these additional respiratory hazards and diseases.</h5>")
print("<h5>Other EMERGING ISSUES IN THE RESPIRATORY DISEASES topic area include Assessing the impact of climate change (temperature extremes, the increased geographic span of allergens, and air quality) on asthma causation and exacerbations. Increasing importance of indoor air quality as a cause of work-related respiratory symptoms and asthma in a service economy. Increasing use of nanotechnology and resulting exposures to engineered nanoparticles.<br>")
print("Increasing exposures to respiratory hazards such as isocyanates used in “green” building materials. Applying knowledge about gene-environment interactions and epigenetics to respiratory disease prevention. Using knowledge about primary causes of asthma (determination of distinct asthma phenotypes) in developing effective prevention strategies, such as weight control and allergen avoidance. Developing novel treatments to alter the progression of disease severity and, ultimately, to prevent asthma onset.<br>")
print("Using personalized medicine (tailoring treatment to a patient’s specific phenotype, genetics, and history). <br>Identifying new respiratory hazards, as has been done during the last decade for diacetyl and other butter-flavoring chemicals; nylon, rayon, and polypropylene flock; and World Trade Center dust. Improving COPD awareness and clinical case-finding in the population at large, and in the health care delivery system at the state and local levels. Establishing a surveillance system for COPD.<br>")
print("<br><br><br>")
print("            <div id='RESPIRATORY DISEASE PREVENTION'>")
print("<h3>RESPIRATORY DISEASE PREVENTION</h3>")
print("<ul><h5>")
print("<li>• Fortunately, most respiratory diseases are PREVENTABLE by improving the quality of the air. Common sources of unhealthy air are tobacco smoke, indoor and outdoor air pollution, and air containing microbes, toxic particles, fumes, or allergens.<br></li>")
print("<li>• Discouraging individuals from starting to smoke tobacco and encouraging smokers to quit smoking are the first and most important priorities in preventing COPD.<br></li>")
print("<li>• Asthmatics who smoke have a more rapid decline in lung function than lifelong non-smokers.<br></li>")
print("<li>• Avoiding smoking during pregnancy and avoidance of passive smoke exposure after birth can reduce asthma severity in children.<br></li>")
print("<li>•Reducing air pollution saves lives and reduces the risk of many diseases. <br></li>")
print("<li>• Vaccinations are essential for the control and elimination of many childhood respiratory diseases.<br></li>")
print("<li>• Controlling unhealthy air in the workplace can prevent occupational lung disease. <br></li>")
print("<li>• Most cases of TB can be cured if diagnosed early and treated appropriately.</li>")
print("<li>• Lung cancer is largely preventable through tobacco control. <br></li>")
print("<li>• Environmental causes of lung cancer, such as air pollution, radon, and asbestos, can be monitored and reduced.<br></li></h5>")

print("            <br/>")
print("        </div>")
print("    </div>")
print(" </body>")
print(" </html>")
