#!C:\Program Files\Python310\python.exe
import cgi, cgitb
#import Mysqldb
cgitb.enable()
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("    <title> RESPIRATORY ILLNESS </title>")
print("   ")
print("    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>")
print("<script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>")
print("<script src='https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js' integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q' crossorigin='anonymous'></script>")
print("<link rel='stylesheet' href='dot.css'>")
print("</head>")
print("")
print("<body>")
print("    <div>  ")
print("        <nav class='navbar navbar-expand-sm navbar-light' style='background-color:#98FB98'>")
print("            <a class='navbar-brand' >")
print("                <img src='logo.png' width='100' height='100' /> RESPIRATORY ILLNESS </a>")
print("            <ul class='navbar-nav ml-auto'>")
print("                <li class='nav-item'>")
print("                    <a class='nav-link' href='main.py'>Home</a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>About </a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>Contact us</a>")
print("                </li>")
print("            </ul>")
print("        </nav>")
print("    </div>")
print("")
print("	")
print("	")
print("<h1><b><center><u>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp EPIDEMIOLOGY TRENDS OF RESPIRATORY DISEASES</CENTER></b></h1>")
print("")
print(" <div class='wrapper'>")
print("        <!--Top menu -->")
print("        <div class='sidebar' style='max-width: 20%;'>")
print("           <!--profile image & text-->")
print("            <!--menu item-->")
print("			<ul>")
print("                <li>")
print("                    <a href='#LUNG CANCER' class='active'>")
print("                        <span class='item'>LUNG CANCER</span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#TUBERCULOSIS' class = 'active'>")
print("                        <span class='item'>TUBERCULOSIS</span>")
print("                    </a>")
print("                </li>")
print("                <li>")
print("                    <a href='#COPD' class='active'>")
print("                        <span class='item'>COPD</span>")
print("                    </a>")
print("                </li>")
print("        </div>")
print("		<div style='max-width: 80%;padding-left: 20%;'><br>")
print("            <div id='LUNG CANCER'>")
print("<h4> LUNG CANCER</h4>")
print("            <h5>The prevalence of lung cancer varies around the world, reflecting regional variances in cigarette usage and air quality. Lung cancer is becoming more common around the world. Lung cancer rates in males are significantly higher in developed countries than in developing countries, owing primarily to smoking behaviors, however, the total incidence of lung cancer in men in affluent countries is declining due to tobacco control laws.</h5>")
print("")
print("            <h5> In the developed world, lung cancer in women is also more common and is connected to cigarette smoking. Female lung cancer is becoming more common in the world. For example, female lung cancer incidence has been climbing throughout Europe for most of the twenty-first century, and in 2017 lung cancer fatality rates surpassed breast cancer mortality rates for the first time, with 14.6 lung cancer deaths per 100,000 compared to 14 breast cancer deaths per 100,000.")
print(" <br>Indoor air pollution and occupational exposures play a bigger influence on female lung cancer in several locations, particularly in Asia. Within areas, there is significant geographical and ethnic heterogeneity in lung cancer incidence and death, just as there is in the United States. Compared to low-income countries, higher-income countries have higher survival rates. The recent spike in cigarette usage in nations like China, where 65% of males start smoking by their mid-20s, portends a lung cancer epidemic in the coming decades.     </h5>    <br/>")
print ("<img src='asian.jpg' height='320' width='670' >")
print("<p><b>Frequencies of prevalent lung cancer driver mutations in the United States and Europe. By demographic category (B) and overall frequency (A) (B). The data are from large clinicopathologic cohort studies that have been published since 2008 and are representative of populations in the United States and Europe.</b></p>")
print("            <br/>")
print("<div id='TUBERCULOSIS'>")
print("            <h4>TUBERCULOSIS</h4>")
print("            <h5>Tuberculosis is contagious and spreads through the air. It is a poverty-related illness that thrives where social and economic determinants of poor health exist, and it primarily affects young adults in their most productive years; 95 percent of tuberculosis deaths occur in underdeveloped countries. It is believed that one-third of the world's population is infected with tuberculosis bacteria. only a small percentage of these infected will become unwell with TB but people with weakened immune systems have a miles more chance of falling sick from TB specifically, someone living with HIV is over 15 times more likely to broaden energetic TB. </h5>")
print("<h5>We understand from historic records that, left untreated, smear-tremendous TB has a ten-12 months case fatality variously stated among 53 and 86%, with a weighted suggest of 70%, compared with 3% of HIV-uninfected dealt with patients with TB expected to die due to TB.</h5>")
print ("<img src='map.png' height='670' width='750' >")
print("            <br><br><br><br><br>")
print ("<img src='blue.png' height='500' width='750' >")
print("<p><b>Countries in which national population-based surveys of the prevalence of pulmonary TB have been implemented using currently recommended screening and diagnostic methods50 since 2000 or are planned in the near future.</b></p>")
print("            <br><br><br>")
print ("<img src='graph.jpg' height='500' width='800' >")
print("<p><b>Worldwide traits in expected tuberculosis (TB) incidence and estimated TB mortality.<br> <br>Left : international tendencies in estimated occurrence including human immunodeficiency virus (HIV)-terrible and HIV-nice TB (gray) and predicted prevalence of HIV-tremendous TB (red). The solid black line shows worldwide developments in case notification rates (all varieties of TB). note: Case notification prices are constantly decrease than occurrence because of neglected cases (detected but no longer reported or not detected). <br>Right : global tendencies in expected TB mortality together with TB-associated received immunodeficiency syndrome (AIDS) deaths (grey), in HIV- bad cases (blue), in HIV-effective instances (crimson). Shaded regions constitute uncertainty bands.</b></p>")
print("            <br><br><br>")
print("            <div id='COPD'>")
print("<h3>COPD (CHRONIC OBSTRUCTIVE PULMONARY DISEASE)</h3>")
print("COPD is a leading cause of death and disability worldwide. COPD is diagnosed by spirometry in 5 to 15 percent of persons in developed countries. COPD was ranked twelfth in the world in terms of combined death and disability in 1990, but it is anticipated to rise to fifth by 2020. <br/>")
print("COPD is defined by an irreversible drop in forced expiratory volume in one second (FEV1), an increase in the presence of dysapnea and other respiratory symptoms, and a progressive decline in health status. The 10-year survival rate after diagnosis is 50%, with more than one-third of patients dying from respiratory insufficiency.<br>")
print(" <br> COPD patients are at an increased risk of death due to a variety of environmental factors, such as air pollution. Although numerous other factors may play a part in COPD etiology, smoking is the most common cause. Although little is known about which genes are involved, certain genetic variations are expected to increase vulnerability to environmental influences. Although there is strong evidence for the significance of a-1 antitrypsin, the proportion of COPD caused by the relevant variations is just 1%. ")
print("   <br/>")
print(" Females being at a higher risk, bronchial reactivity, and atopy are all phenotypic features that are thought to play a role in the development of COPD. The link between smoking and COPD has strong causal evidence, with the fall in FEV1 leveling off following smoking cessation.")
print("<br>Passive smoking has been linked to a slight, but statistically significant, reduction in FEV1. Other risk factors for COPD development include occupation, low socioeconomic level, nutrition, and possibly early environmental exposures. Despite mounting evidence that oxygen therapy, pharmaceutical treatment, and rehabilitation may alter the course of chronic obstructive pulmonary disease, quitting smoking remains the most important approach for not just avoiding but also arresting the illness's progression.            <br/>")
print ("<img src='smoke.png' height='500' width='500' >")
print("<p><right><b>Prevalence of the continual obstructive pulmonary disorder in line with demographic standards</b> </right></p>")
print("            <br>")
print ("<img src='bronchitis.jpg' height='500' width='650' >")
print("            <br><br><br>")
print("<h2>REFERENCES</h2>")
print("1. <a href='https://pubmed.ncbi.nlm.nih.gov/30741509/'> https://pubmed.ncbi.nlm.nih.gov/30741509/</a><br>")
print("2. <a href='https://pubmed.ncbi.nlm.nih.gov/30050761/'> https://pubmed.ncbi.nlm.nih.gov/30050761/</a><br>")
print("3. <a href='https://pubmed.ncbi.nlm.nih.gov/30071543/'> https://pubmed.ncbi.nlm.nih.gov/30071543/</a><br>")
print("4. <a href='https://www.researchgate.net/publication/244894052_Epidemiology_of_Chronic_Obstructive_Pulmonary_Disease_Exacerbations'> https://www.researchgate.net/publication/244894052_Epidemiology_of_Chronic_Obstructive_Pulmonary_Disease_Exacerbations</a><br>")
print("5. <a href='https://err.ersjournals.com/content/18/114/213'> https://err.ersjournals.com/content/18/114/213</a><br>")
print("        </div>")
print("    </div>")
print(" </body>")
print(" </html>")
