#!C:\Program Files\Python310\python.exe
import cgi, cgitb
#import Mysqldb
cgitb.enable()
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("    <title> RESPIRATORY ILLNESS </title>")
print("   ")
print("    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>")
print("<script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>")
print("<script src='https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js' integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q' crossorigin='anonymous'></script>")
print("<link rel='stylesheet' href='dot.css'>")
print("</head>")
print("")
print("<body>")
print("    <div>  ")
print("        <nav class='navbar navbar-expand-sm navbar-light' style='background-color:#98FB98'>")
print("            <a class='navbar-brand' >")
print("                <img src='logo.png' width='100' height='100' /> RESPIRATORY ILLNESS </a>")
print("            <ul class='navbar-nav ml-auto'>")
print("                <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>Home</a>")
print("                </li>")
print("				        <li class='nav-item'>")
print("                    <a class='nav-link' href='about.py'>About </a>")
print("                </li>")
print("				        <li class='nav-item'>")
print("                    <a class='nav-link' href='contact.py'>Contact us</a>")
print("                </li>")
print("            </ul>")
print("        </nav>")
print("    </div>")
print("")
print("<div class='bubbles' style='min-height:10em; min-height:18em'>")
print("	<div class='circles' >")
print("		<div class='circle1'>")
print("			<a id='Asthma' href='chronicpul.py'><b>Copd Severity Assesment</b></a>")
print("		</div>")
print("")
print("		<div class='circle2'>")
print("			<a id='COPD' href='asthma.py'><b>Spirometry Interpretation</b></a>")
print("			 </b></a>")
print("		</div>")
print("		")
# print("		<div class='circle3'>")
# print("			<a id='Lungcancer' href='#'><b>Lungcancer</b></a>")
# print("		</div>")
print("		<div class='circle4'>")
print("			<a id='Tuberculosis' href='tb.py'><b>TB Prediction</b></a>")
print("		</div>")
print("		")
# print("		<div class='circle5'>")
# print("			<a id='Prediction' class=' dropdown-toggl' href='#' id='dropdownMenuLink' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'><b>Prediction</b></a>")
# print("			  <div class='dropdown-menu' aria-labelledby='dropdownMenuLink'>")
# print("				<a class='dropdown-item' href='chronicpul.py'>Copd</a>")
# print("				<a class='dropdown-item' href='asthma.py'>Pulmonary Function Test</a>")
# print("				<a class='dropdown-item' href='tb.py'>Tuberculosis</a>")
# print("			  </div>")
print("		</div>")
print("	</div>")
print("</div>")
print("<br/>")
print("<br/>")
print("<div class='content container'>")
print("India has 18% of the world’s population but 32% of the global burden of respiratory diseases. Respiratory disease burden in India is second only to that of ischaemic heart disease, found a state-level analysis of the Global Burden of Disease data. Chronic respiratory diseases were responsible for 10.9% of the total deaths and 6.4% of the total DALYs (a globally recognised disease burden estimate calculated on the basis of the number of productive life years cut short by disease) in India in 2016.")
print("</div>")
print("<br/>")
print("<br/>")
print("<div class='row' style='padding-right:2em; padding-left:2em;'> ")
print("  <div class='col-sm-4'>")
print("    <div class='card'>")
print("      <div class='card-body'>")
print("        <h5 class='card-title'><u><b>'Extreme of anything can kill'</b></u></h5>")
print("        <p class='card-text'><a href='copd.py'> CLIMATE CHANGE AND HEALTH CONCERNS </a></p>")
print("      </div>")
print("    </div>")
print("  </div>")
print("  <div class='col-sm-4'>")
print("    <div class='card'>")
print("      <div class='card-body'>")
print("        <p class='card-text'><a href='emerge.py'> EMERGING ISSUES IN THE RESPIRATORY DISEASES  </a></p>")
print("        ")
print("      </div>")
print("    </div>")
print("  </div>")
print("    <div class='col-sm-4'>")
print("    <div class='card'>")
print("      <div class='card-body'>")
print("        <p class='card-text'><a href='epidemiology.py'> EPIDEMIOLOGY TRENDS OF RESPIRATORY DISEASES </a></p>")
print("       </a> ")
print("      </div>")
print("    </div>")
print("  </div>")
print("</div>")
print("")
print("<br/>")
print("<br/>")
print("")
print("</body>")
print("</html>")