#!C:\Program Files\Python310\python.exe
import cgi, cgitb
#import Mysqldb
cgitb.enable()
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("    <title> RESPIRATORY ILLNESS </title>")
print("   ")
print("    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>")
print("<script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>")
print("<script src='https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js' integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q' crossorigin='anonymous'></script>")
print("<link rel='stylesheet' href='dot.css'>")
print("</head>")
print("")
print("<body>")
print("    <div>  ")
print("        <nav class='navbar navbar-expand-sm navbar-light' style='background-color:#98FB98'>")
print("            <a class='navbar-brand' >")
print("                <img src='logo.png' width='100' height='100' /> RESPIRATORY ILLNESS </a>")
print("            <ul class='navbar-nav ml-auto'>")
print("                <li class='nav-item'>")
print("                    <a class='nav-link' href='main.py'>Home</a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>About </a>")
print("                </li>")
print("                     <li class='nav-item'>")
print("                    <a class='nav-link' href='#'>Contact us</a>")
print("                </li>")
print("            </ul>")
print("        </nav>")
print("    </div>")
print("")





print("		")
print("    </div>")
print("	<div class='container'>")
print("		<div>")




print("			<center><h3><b>TB DIAGNOSIS  </b></h3></center>")
print("		</div>")
print("    	<div class='col-sm'>")
print("			<div class='card'>")
print("			  <div class='card-body'>")
print("				<h6 class='card-title'><u><b>SYMPTOMMATIC ASSESSMENT</b></u></h6>")
print("<form action='tb_prediction.py' method='POST'>")
print("				<h7 class='card-title'><b>Do you currently have the following symptoms</b></h7>")
print("				")
print("				<br/>")
print("				<input type='checkbox' id='symptoms_checkbox1' name='symptoms_checkbox' value='Cough for more than 3 weeks'>")
print("				<label for='symptoms_checkbox1'> Cough for more than 3 weeks</label>")
print("				")
print("				<br/>")
print("				")
print("				<input type='checkbox' id='symptoms_checkbox2' name='symptoms_checkbox' value='Unexplained weight loss'>")
print("				<label for='symptoms_checkbox2'> Unexplained weight loss</label>")
print("")
print("				</br>")
print("				<input type='checkbox' id='symptoms_checkbox3' name='symptoms_checkbox' value='Coughing up blood'>")
print("				<label for='symptoms_checkbox3'> Coughing up blood</label><br>")
print("")
print("				<input type='checkbox' id='symptoms_checkbox4' name='symptoms_checkbox' value='Drenching night sweats'>")
print("				<label for='symptoms_checkbox4'> Drenching night sweats</label><br>")
print("")
print("				<input type='checkbox' id='symptoms_checkbox5' name='symptoms_checkbox' value='Chronic fever'>")
print("				<label for='symptoms_checkbox5'>Chronic fever</label><br>")
print("")
print("			    <label for='exampleFormControlFile1'><b>Upload X-Ray (if you have atleast one of the above symptom)</b></label>")
print("			    <input type='file' class='form-control-file' id='symptoms_fileupload' name='symptoms_fileupload'>")
print("				</br>")
print("	")
print("				<button type='submit' class='btn btn-primary'>Submit</button>")
print("  				<br/>")
print("</form>")
print("  			</div>")
print("  		</div>	<br></br>")
print("")
print("		<div class='col-sm'>")
print("			<div class='card'>")
print("			  <div class='card-body'>")
print("				<h6 class='card-title'><u><b>MANTOUX TEST (Tuberculin Skin test)</b></u></h6>")
print("				<h7 class='card-title'><b>1)	Measurement</b></h7>")
print("				<form action='MANTOUX_output.py' method='GET/POST'>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='mantoux_checkbox' id='mantoux_checkbox1' value='5mm'>")
print("			  <label class='form-check-label' for='mantoux_checkbox1'>5mm</label>")
print("			</div>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='mantoux_checkbox' id='mantoux_checkbox2' value='10mm'>")
print("			  <label class='form-check-label' for='mantoux_checkbox2'>10mm</label>")
print("			</div>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='mantoux_checkbox' id='mantoux_checkbox3' value='15mm'>")
print("			  <label class='form-check-label' for='mantoux_checkbox3'>15mm</label>")
print("			</div>")
print("			<br></br>")
print("")
print("")
print("				<h7 class='card-title'><b>2)	Risk factors</b></h7>")
print("				<br></br>")
print("				")
print("				<input type='checkbox' id='risk_factor_checkbox1' name='risk_factor_checkbox' value='HIV positive / immunodeficiency state'</label>")
print("				<label for='risk_factor_checkbox1'> HIV positive / immunodeficiency state</label>")
print("")
print("				</br>")
print("				<input type='checkbox' id='risk_factor_checkbox2' name='risk_factor_checkbox' value='Recent contact with active TB patient'>")
print("				<label for='risk_factor_checkbox2'> Recent contact with active TB patient</label><br>")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox3' name='risk_factor_checkbox' value='X ray finding of old Tb'>")
print("				<label for='risk_factor_checkbox3'> X ray finding of old Tb</label><br>")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox4' name='risk_factor_checkbox' value='Mycobacteriology Lab personnel'>")
print("				<label for='risk_factor_checkbox4'> Mycobacteriology Lab personnel</label><br>")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox5' name='risk_factor_checkbox' value='Children <4 years old'>")
print("				<label for='risk_factor_checkbox5'> Children <4 years old </label><br>")
print("			")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox6' name='risk_factor_checkbox' value='Co-morbid conditions'>")
print("				<label for='risk_factor_checkbox6'> Co-morbid conditions</label>")
print("")
print("				</br>")
print("				<input type='checkbox' id='risk_factor_checkbox7' name='risk_factor_checkbox' value='IV drug users'>")
print("				<label for='risk_factor_checkbox7'> IV drug users</label><br>")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox8' name='risk_factor_checkbox' value='Nursing home residents'>")
print("				<label for='risk_factor_checkbox8'> Nursing home residents</label><br>")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox9' name='risk_factor_checkbox' value='Malnutrition, Steroid use, Diabetes'>")
print("				<label for='risk_factor_checkbox9'>Malnutrition, Steroid use, Diabetes</label><br>")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox10' name='risk_factor_checkbox' value='Organ transplant'>")
print("				<label for='risk_factor_checkbox10'> Organ transplant</label><br>")
print("			")
print("				<input type='checkbox' id='risk_factor_checkbox11' name='risk_factor_checkbox' value='Travellers from endemic or high risk areas of TB'>")
print("				<label for='risk_factor_checkbox11'> Travellers from endemic or high risk areas of TB</label>")
print("")
print("				</br>")
print("				<input type='checkbox' id='risk_factor_checkbox12' name='risk_factor_checkbox' value='Homeless'>")
print("				<label for='risk_factor_checkbox12'> Homeless </label><br>")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox13' name='risk_factor_checkbox' value='Prisoners'>")
print("				<label for='risk_factor_checkbox13'> Prisoners </label><br>")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox14' name='risk_factor_checkbox' value='Chronic fever'>")
print("				<label for='risk_factor_checkbox14'>Chronic fever</label><br>")
print("")
print("				<input type='checkbox' id='risk_factor_checkbox15' name='risk_factor_checkbox' value='No known risk factors'>")
print("				<label for='risk_factor_checkbox15'>No known risk factors</label><br>")
print("")
print("			")
print("				</br>")
print("				<button type='submit' class='btn btn-primary'>Submit</button>")
print("		</form>")
print("			</div>")
print("		</div>")
print("	</div>")
print("	<br></br>")
print("	")
print("	<div class='col-sm'>")
print("			<div class='card'>")
print("			  <div class='card-body'>")
print("				<h6 class='card-title'><u><b>SPUTUM SMEAR GRADING</b></u></h6>")
print("				<h7 class='card-title'><b>Grading</b></h7>")
print("			<form action='SPUTUM_output.py' method='GET/POST'>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='sputum_radiobox' id='sputum_radiobox1' value='Negative'>")
print("			  <label class='form-check-label' for='sputum_radiobox1'>Negative</label>")
print("			</div>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='sputum_radiobox' id='sputum_radiobox3' value='1+'>")
print("			  <label class='form-check-label' for='sputum_radiobox3'>1+</label>")
print("			</div>")
print("		</br>")
print("")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='sputum_radiobox' id='sputum_radiobox4' value='2+'>")
print("			  <label class='form-check-label' for='sputum_radiobox4'>2+</label>")
print("			</div>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='sputum_radiobox' id='sputum_radiobox5' value='3+'>")
print("			  <label class='form-check-label' for='sputum_radiobox5'>3+</label>")
print("			</div>")
print("			<br/>")
print("			<div class='form-check form-check-inline'>")
print("			  <input class='form-check-input' type='radio' name='sputum_radiobox' id='sputum_radiobox6' value='4+'>")
print("			  <label class='form-check-label' for='sputum_radiobox6'>4+</label>")
print("			</div>")
print("			<br></br>")
print("")
print("			<button type='submit' class='btn btn-primary'>Submit</button>")
print("")
print("		</form>")
print("        </div>")
print("    </div>")
print("    <br><br/>")
print("</div>")
print("</div>")
print("</div>")
